### ISSUE TITLE
Bug: maven server id did not show the correct list from the setings.xml

### ISSUE THREAD

**Issue by Happy-ArthurYang** [coderazzi/aws_codeartifact_maven#14]
when I try to work with my mutiple maven repos the list of Maven server Id in the UI did not show all of my server Id in the seetings.xml
![image](https://github.com/coderazzi/aws_codeartifact_maven/assets/113080404/b3de6d2c-a8d0-4f20-a0a2-d5c3f516a4b7)
Below is my seetiings.xml snapsho, there are 4 servers .
![image](https://github.com/coderazzi/aws_codeartifact_maven/assets/113080404/a02d148f-2fdf-4bed-9028-86fe3cac28fc)

the expect result is the UI could list all my server in the dropdown list

**Comment by coderazzi** [comment]
Hi, there is a refresh button for that field on the plugin, so it only
parses the settings.xml once, or when needed.
If that doesn't work, could you send me your settings. XML file,?
Best
L.

**Comment by Happy-ArthurYang** [comment]
will continue to observe, seems not work every time, especially for my wrapper script scenario. There is a long string to show the script.
![image](https://github.com/coderazzi/aws_codeartifact_maven/assets/113080404/29a0cfa3-11f3-461a-b567-efeebba55b01)

**Comment by coderazzi** [comment]
Hi, indeed, that looks very bad,
Your bat script is now something like:

C:\MyApps\JetBrains....\aws %* --no-verify-ssl

Try having

@C:\MyApps\JetBrains....\aws %* --no-verify-ssl

This way, the line itself won't be included in the output,

Best,
 L.

**Comment by Happy-ArthurYang** [comment]
[getTokenForGenie.txt](https://github.com/coderazzi/aws_codeartifact_maven/files/12925590/getTokenForGenie.txt)
[getTokenForTlm.txt](https://github.com/coderazzi/aws_codeartifact_maven/files/12925591/getTokenForTlm.txt)
[getTokenForTlp.txt](https://github.com/coderazzi/aws_codeartifact_maven/files/12925592/getTokenForTlp.txt)
[getTokenForTmc.txt](https://github.com/coderazzi/aws_codeartifact_maven/files/12925594/getTokenForTmc.txt)
I list all my scripts just change the ext from .cmd to .txt

**Comment by Happy-ArthurYang** [comment]
this is the UI before click GEnerate Credentials button.
![image](https://github.com/coderazzi/aws_codeartifact_maven/assets/113080404/d722ee3b-5161-4a24-9b6b-d1c40c62ce05)

**Comment by coderazzi** [comment]
Hi, your scriptgetTokenForGenie.cmd
should be:

@aws codeartifact get-authorization-token --domain genie-domain
--domain-owner 380723925535 --query authorizationToken --output text
 --profile genie-ss --no-verify-ssl

instead of

aws codeartifact get-authorization-token --domain genie-domain
--domain-owner 380723925535 --query authorizationToken --output text
 --profile genie-ss --no-verify-ssl

(attention to the first @ character)

But I think that your approach is wrong. In this moment, when you change
the profile, you change as well the AWS cli path. You could have just one
single script, not one per profile, and that script would look like:

@aws --no-verify-ssl %*

Best,

 L.

**Comment by Happy-ArthurYang** [comment]
yes [@aws](https://github.com/aws) --no-verify-ssl %* works fine, thank you for your help.
